apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-slim-app
  template:
    metadata:
      labels:
        app: react-slim-app
    spec:
      containers:
      - name: react-app-kube
        image: ikegabriel/react-starter-2020:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: react-slim-service
spec:
  selector:
    app: react-slim-app
  ports:
  - port: 5000
    targetPort: 80
    protocol: "TCP"
  
  type: LoadBalancer